config/routes.rb
require "resque/server"
require 'resque_scheduler'
require 'resque_scheduler/server'
require 'resque-pause/server'
require 'resque-history/server'

Resque.schedule = YAML.load_file(File.join(Rails.root, 'config/resque_schedule.yml'))

Smsreply::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users

  root :to => "messages#index"
  get "messages/received" => "messages#received"
  get "messages/sent" => "messages#sent"
  resources :messages, :only=>[:index, :create, :show]

  resources :phone_number_setups do
    resources :away_calendars
  end
  resources :replies, :only=>[:index]
  resources :nexmo, :only=>[:index, :create]

  mount Resque::Server.new, :at => "/resque"

end

app/models/message.rb
class Message < ActiveRecord::Base

  paginates_per 25

  belongs_to :user
  belongs_to :phone_number_setup

  has_many :response_messages

  has_many :user_responder_messages, :through => :response_messages

  attr_accessible :received, :destination, :origin, :direction, :message_type,
                  :reply_message_id, :replied_on, :user,
                  :phone_number_setup, :reply_text

  def clear_autoreply!
    update_attributes(:replied_on=>nil,
                      :reply_message_id=>nil,
                      :reply_text=>nil)
  end

  def reply_text
    response_messages.try(:first).try(:reply_text)
  end

  def message_id
    response_messages.try(:first).try(:message_id)
  end

  def replied_on
    response_messages.try(:first).try(:replied_on)
  end

  def reply_message_id
    response_messages.try(:first).try(:reply_message_id)
  end

end

app/controllers/messages_controller.rb
require 'csv'

class MessagesController < ApplicationController

  def index
    redirect_to messages_received_path
  end

  def received
    @messages = current_user.messages.order("received DESC").where(:direction=>"Received").page(params[:page])
  end

  def sent
    @messages = current_user.messages.order("received DESC").where(:direction=>"Sent").page(params[:page])
  end

  def show
    @message = current_user.messages.find(params[:id])
  end

  def create

    current_user.phone_number_setups.where(provider_id: Provider.find_by_name(Provider::VERIZON)).each do |phone|
      Providers::VerizonMessagesJob.perform(phone.id)
    end

    redirect_to messages_path

  end
end

app/views/messages/_common.html.erb
<%= link_to "Get latest data", messages_url, :method=>:post %>  |
<%= link_to "Send replies", replies_url %> |
<%= link_to "Received messages", messages_received_path %> |
<%= link_to "Sent messages", messages_sent_path %> |
<br/>

app/views/messages/received.html.erb
<%=render :partial=>"common"%>

Received messages

<%= paginate @messages %>

<table border="1">
  <th>Id</th>
  <th>Date</th>
  <th>Destination</th>
  <th>Origin</th>
  <th>Autoreplied</th>
  <th>Autoreplied message</th>
  <th>Autoreplied text</th>
  <th>Response</th>

  <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= I18n.l(message.received, :format=>:short) %></td>
        <td><%= message.destination %></td>
        <td><%= message.origin %></td>
        <td><%= I18n.l(message.replied_on, :format=>:short) if message.replied_on and message.reply_message_id.nil? %></td>
        <td><%= message.reply_message_id %></td>
        <td><%= message.reply_text %></td>
        <td><%= link_to("see response", message) if message.user_responder_messages.count > 0 %></td>
      </tr>

  <% end %>
</table>

<%= paginate @messages %>

app/views/messages/sent.html.erb
<%=render :partial=>"common"%>

Sent messages

<%= paginate @messages %>

<table border="1">
  <th>Id</th>
  <th>Date</th>
  <th>Destination</th>

  <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= I18n.l(message.received, :format=>:short) %></td>
        <td><%= message.destination %></td>
      </tr>

  <% end %>
</table>

<%= paginate @messages %>

app/views/messages/show.html.erb
<div><%= @message.id %></div>
<div><%= I18n.l(@message.received, :format=>:short) %></div>
<div><%= @message.destination %></div>
<div><%= @message.origin %></div>
<br/>
Autoreponse sent
<br/>
<div><%= I18n.l(@message.replied_on, :format=>:short) if @message.replied_on and @message.reply_message_id.nil? %></div>
<div><%= @message.reply_message_id %></div>
<div><%= @message.reply_text %></div>

<br/>
User reponded to your away message
<br/>
<div>
  <% @message.user_responder_messages.each do |message| %>
      <div><%= message.text %></div>
  <% end %>
</div>