config/routes.rb
require "resque/server"
require 'resque_scheduler'
require 'resque_scheduler/server'
require 'resque-pause/server'
require 'resque-history/server'

Resque.schedule = YAML.load_file(File.join(Rails.root, 'config/resque_schedule.yml'))

Smsreply::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users

  root :to => "messages#index"
  get "messages/received" => "messages#received"
  get "messages/sent" => "messages#sent"
  resources :messages, :only=>[:index, :create, :show]

  resources :phone_number_setups do
    resources :away_calendars
  end
  resources :replies, :only=>[:index]
  resources :nexmo, :only=>[:index, :create]

  mount Resque::Server.new, :at => "/resque"

end

app/models/away_calendar.rb
class AwayCalendar < ActiveRecord::Base
  attr_accessible :end_at, :message, :phone_number_setup_id, :start_at, :last_run

  scope :current, where("start_at <= ? ", Time.now).where("end_at >= ?", Time.now)

  validates_presence_of :end_at
  validates_presence_of :start_at
  validates_presence_of :message

  belongs_to :phone_number_setup
  has_many :messages, :through=>:phone_number_setup

  #TODO: make sure there are no overlappings
end

app/controllers/away_calendars_controller.rb
class AwayCalendarsController < ApplicationController
  # GET /away_calendars
  # GET /away_calendars.json
  def index
    @away_calendars = current_user.away_calendars
    @phone_setup = current_user.phone_number_setups.find(params[:phone_number_setup_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @away_calendars }
    end
  end

  # GET /away_calendars/1
  # GET /away_calendars/1.json
  def show
    @away_calendar = current_user.away_calendars.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @away_calendar }
    end
  end

  # GET /away_calendars/new
  # GET /away_calendars/new.json
  def new
    @phone_setup = current_user.phone_number_setups.find(params[:phone_number_setup_id])
    @away_calendar = AwayCalendar.new(:phone_number_setup_id=>@phone_setup)

    respond_to do |format|
      format.html
    end
  end

  # GET /away_calendars/1/edit
  def edit
    @phone_setup = current_user.phone_number_setups.find(params[:phone_number_setup_id])
    @away_calendar = AwayCalendar.find(params[:id])
  end

  # POST /away_calendars
  # POST /away_calendars.json
  def create
    @phone_setup = current_user.phone_number_setups.find(params[:phone_number_setup_id])
    @away_calendar = AwayCalendar.new(params[:away_calendar])
    @away_calendar.phone_number_setup=@phone_setup

    respond_to do |format|
      if @away_calendar.save
        format.html { redirect_to [@phone_setup,@away_calendar], notice: 'Away calendar was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /away_calendars/1
  # PUT /away_calendars/1.json
  def update
    @away_calendar = current_user.away_calendars.find(params[:id])
    @phone_setup = current_user.phone_number_setups.find(params[:phone_number_setup_id])

    respond_to do |format|
      if @away_calendar.update_attributes(params[:away_calendar])
        format.html { redirect_to [@phone_setup,@away_calendar], notice: 'Away calendar was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /away_calendars/1
  # DELETE /away_calendars/1.json
  def destroy
    @away_calendar = AwayCalendar.find(params[:id])
    @away_calendar.destroy

    respond_to do |format|
      format.html { redirect_to away_calendars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/away_calendars_helper.rb
module AwayCalendarsHelper
end

app/views/away_calendars/_form.html.erb
<%= javascript_include_tag "calendar"%>
<%= stylesheet_link_tag "calendar", :media => "all" %>

<%= semantic_form_for [@phone_setup,@away_calendar] do |f| %>
    <%= f.inputs do %>
        <%= f.input :message %>
        <%= f.input :start_at, :as => :ui_date_picker, :input_html=>{:format=>'%m %d %Y'}  %>
        <%= f.input :end_at, :as => :ui_date_picker, :input_html=>{:format=>'%b %d %Y'}  %>
    <% end %>
    <%= f.actions %>
<% end %>

app/views/away_calendars/edit.html.erb
<h1>Editing away_calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', [@phone_setup,@away_calendar] %> |
<%= link_to 'Back', phone_number_setup_away_calendars_path(@phone_setup) %>

app/views/away_calendars/index.html.erb
<h1>Listing away_calendars</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @away_calendars.each do |away_calendar| %>
  <tr>
    <td><%=away_calendar.message%></td>
    <td><%=I18n.l away_calendar.start_at, :format=>:long%></td>
    <td><%=I18n.l away_calendar.end_at, :format=>:long%></td>
    <td><%= link_to 'Show', [@phone_setup,away_calendar] %></td>
    <td><%= link_to 'Edit', edit_phone_number_setup_away_calendar_path(@phone_setup, :id=>away_calendar) %></td>
    <td><%= link_to 'Destroy', [@phone_setup,away_calendar], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Away calendar', new_phone_number_setup_away_calendar_path(@phone_setup) %>

app/views/away_calendars/new.html.erb
<h1>New away_calendar</h1>
Format of dates is screwed up

<%= render 'form' %>

<%= link_to 'Back', phone_number_setup_away_calendars_path(@phone_setup) %>

app/views/away_calendars/show.html.erb
<p id="notice"><%= notice %></p>


<%= @away_calendar.message %>
<br/>
<%= @away_calendar.start_at%>
<br/>
<%= @away_calendar.end_at %>
<br/>
<%= link_to 'Edit', edit_phone_number_setup_away_calendar_path(@phone_setup, :id=>@away_calendar) %> |
<%= link_to 'Back', phone_number_setup_away_calendars_path(@phone_setup) %>