config/routes.rb
require "resque/server"
require 'resque_scheduler'
require 'resque_scheduler/server'
require 'resque-pause/server'
require 'resque-history/server'

Resque.schedule = YAML.load_file(File.join(Rails.root, 'config/resque_schedule.yml'))

Smsreply::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users

  root :to => "messages#index"
  get "messages/received" => "messages#received"
  get "messages/sent" => "messages#sent"
  resources :messages, :only=>[:index, :create, :show]

  resources :phone_number_setups do
    resources :away_calendars
  end
  resources :replies, :only=>[:index]
  resources :nexmo, :only=>[:index, :create]

  mount Resque::Server.new, :at => "/resque"

end

app/models/phone_number_setup.rb
class PhoneNumberSetup < ActiveRecord::Base
  attr_accessible :password, :url, :user_id, :username, :provider_id, :phone

  belongs_to :user
  has_many :messages, :through=>:user
  has_many :away_calendars

  belongs_to :provider

  validates_presence_of :password, :username, :provider, :phone
  validates_uniqueness_of :phone

  before_save :validate_with_provider

  private

  def validate_with_provider

    if provider.name == Provider::VERIZON
      self.url = "https://nbillpay.verizonwireless.com/vzw/accountholder/unbilledusage/UnbilledMessaging.action?d-4019015-e=2&6578706f7274=1&mtn=#{phone}&tab=messages"
      return validate_verizon
    else
      self.errors.add :provider, "Invalid provider"
      return false
    end

  end

  def validate_verizon

    # create Mechanize instance
    agent = Mechanize.new { |a|
      a.user_agent_alias = 'Mac Safari'
    }

    # get the login form & fill it out with the username/password
    login_form = agent.get(self.url).form('loginForm')
    login_form.IDToken1 = self.username
    login_form.IDToken2 = self.password

    # submit login form
    res = agent.submit(login_form, login_form.buttons.first)

    #if we succeed, a file will be returned, not a page
    if res.class == Mechanize::Page and res.try(:title) =~ /Sign In/
      self.errors.add :provider, "Unable to connect to 'Verizon Wireless'. Please check the information provided"
      return false
    elsif res.class == Mechanize::File
      return true
    end

    self.errors.add :provider, "Unable to verify provider. Please contact support"
    false

  end
end

app/controllers/phone_number_setups_controller.rb
class PhoneNumberSetupsController < ApplicationController
  # GET /phone_number_setups
  # GET /phone_number_setups.json
  def index
    @phone_number_setups = current_user.phone_number_setups

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phone_number_setups }
    end
  end

  # GET /phone_number_setups/1
  # GET /phone_number_setups/1.json
  def show
    @phone_number_setup = current_user.phone_number_setups.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phone_number_setup }
    end
  end

  # GET /phone_number_setups/new
  # GET /phone_number_setups/new.json
  def new
    @phone_number_setup = PhoneNumberSetup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone_number_setup }
    end
  end

  # GET /phone_number_setups/1/edit
  def edit
    @phone_number_setup = current_user.phone_number_setups.find(params[:id])
  end

  # POST /phone_number_setups
  # POST /phone_number_setups.json
  def create
    @phone_number_setup = PhoneNumberSetup.new(params[:phone_number_setup])
    @phone_number_setup.user = current_user

    respond_to do |format|
      if @phone_number_setup.save
        format.html { redirect_to @phone_number_setup, notice: 'Phone number setup was successfully created.' }
        format.json { render json: @phone_number_setup, status: :created, location: @phone_number_setup }
      else
        format.html { render action: "new" }
        format.json { render json: @phone_number_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phone_number_setups/1
  # PUT /phone_number_setups/1.json
  def update
    @phone_number_setup = current_user.phone_number_setups.find(params[:id])

    respond_to do |format|
      if @phone_number_setup.update_attributes(params[:phone_number_setup])
        format.html { redirect_to @phone_number_setup, notice: 'Phone number setup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone_number_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_number_setups/1
  # DELETE /phone_number_setups/1.json
  def destroy
    @phone_number_setup = PhoneNumberSetup.find(params[:id])
    @phone_number_setup.destroy

    respond_to do |format|
      format.html { redirect_to phone_number_setups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/phone_number_setups_helper.rb
module PhoneNumberSetupsHelper
end

app/views/phone_number_setups/_form.html.erb
<%= semantic_form_for @phone_number_setup do |f| %>
    <%= f.inputs do %>
        <%=f.input :phone%>
        <%=f.input :username%>
        <%=f.input :password%>
        <%=f.input :provider%>
    <% end %>
    <%= f.actions %>
<% end %>

app/views/phone_number_setups/edit.html.erb
<h1>Editing phone_number_setup</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number_setup %> |
<%= link_to 'Back', phone_number_setups_path %>

app/views/phone_number_setups/index.html.erb
<h1>Listing phone_number_setups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phone_number_setups.each do |phone_number_setup| %>
  <tr>
    <td><%=phone_number_setup.phone%></td>
    <td><%= link_to 'Show', phone_number_setup %></td>
    <td><%= link_to 'Edit', edit_phone_number_setup_path(phone_number_setup) %></td>
    <td><%= link_to 'Destroy', phone_number_setup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phone number setup', new_phone_number_setup_path %>

app/views/phone_number_setups/new.html.erb
<h1>New phone_number_setup</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_number_setups_path %>

app/views/phone_number_setups/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_phone_number_setup_path(@phone_number_setup) %> |
<%= link_to 'Back', phone_number_setups_path %>