config/routes.rb
require "resque/server"
require 'resque_scheduler'
require 'resque_scheduler/server'
require 'resque-pause/server'
require 'resque-history/server'

Resque.schedule = YAML.load_file(File.join(Rails.root, 'config/resque_schedule.yml'))

Smsreply::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users

  root :to => "messages#index"
  get "messages/received" => "messages#received"
  get "messages/sent" => "messages#sent"
  resources :messages, :only=>[:index, :create, :show]

  resources :phone_number_setups do
    resources :away_calendars
  end
  resources :replies, :only=>[:index]
  resources :nexmo, :only=>[:index, :create]

  mount Resque::Server.new, :at => "/resque"

end

app/views/layouts/_header.html.erb
<%= link_to "Messages", messages_url%> |
<% if current_user and current_user.phone_number_setups.present? %>
    <%= link_to "Away calendars", phone_number_setup_away_calendars_path(current_user.phone_number_setups.first) %> |
    <%= link_to 'New Away calendar', new_phone_number_setup_away_calendar_path(current_user.phone_number_setups.first) %>  |
<% end %>
<%= link_to 'New Phone number setup', new_phone_number_setup_path %> |
<%= link_to "Sign out", destroy_user_session_path(), :method=>:delete %><br />
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smsreply</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.17/themes/ui-lightness/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <style>
    #tipbtn {
      float: right;
      cursor: pointer;
    }
  </style>
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js" type="text/javascript"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.17/jquery-ui.min.js" type="text/javascript"></script>
  <script src="http://mrcote.info/tipjar/tipjar.js"></script>
  <script>
    $(document).ready(function () {
      tipjar($("#tipbtn"), '1310000000023328', 0.05);
    });
  </script>

  <%= csrf_meta_tags %>
</head>
<body>


<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>

<%= render :partial => "layouts/header" %>

<%= yield %>

<br/>
<%= link_to "View full site", url_for(:full_site => 1) %>
<%= link_to "View mobile site", url_for(:mobile_site => 1) %>

</body>
</html>